name: 'wrike-ist'
description: 'GitHub Action for Wrike automation'
runs:
  using: 'node12'
  main: 'resources/index.js'
branding:
  color: green
  icon: check-square
inputs:
  open:
    required: false
    description: Status to move task to when the PR is (re)opened. Defaults to the first Active status in your workflow.
  merged:
    required: false
    description: Status to move task to when the PR is merged. Defaults to the first Completed status in your workflow.
  closed:
    required: false
    description: Status to move task to when the PR is closed without merging. Defaults to the first Cancelled status in your workflow.
